apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-dapr-master:6379
  - name: redisPassword
    secretKeyRef:
      name: redis-dapr
      key: redis-password
auth:
  secretStore: kubernetes